### ISSUE TITLE
When Atom is in Zen Mode the minimap is "squashed"

### ISSUE THREAD

**Issue by toastking** [fundon/atom-minimap#131]
When you first enter zen mode the minimap looks like this:
![screen shot 2014-09-25 at 1 58 22 pm](https://cloud.githubusercontent.com/assets/1754099/4409458/9dab6cec-44dd-11e4-9127-d29b537b231d.png)

Until you press the plugin settings icon (the gear) and toggle an option.  Then it goes back to normal.

**Comment by abe33** [comment]
This specific issue was fixed with v4. Closing the issue.
