### ISSUE TITLE
No code preview displayed on minimap

### ISSUE THREAD

**Issue by Kamilius** [fundon/atom-minimap#155]
Minimap on my right is blank with only area for dragging available.
![screenshot from 2014-11-25 15 58 35](https://cloud.githubusercontent.com/assets/3115794/5183948/f95aa874-74bb-11e4-9da8-096b098f2a3f.png)

How to make code "preview" to appear on minimap same, is it is on this package's Github page?
Thanks.

P.s.: Minimap version - 3.3.13, Atom - v0.152.0

**Comment by abe33** [comment]
@Kamilius If you feel to get your hand a bit dirty you can try installing locally the `feature_html_element` branch that I use to progress on v4. The approach is a bit different so maybe your issue will be solved.

**Comment by Kamilius** [comment]
@abe33 Thanks, but I now don't have an access to "buggy" laptop, and this works fine on my current working machine.

**Comment by fundon** [comment]
@Kamilius In the latest version(v4.1.4), is there this issue?

**Comment by fundon** [comment]
There is still same issue, re-open it please.
