### ISSUE TITLE
Uncaught TypeError: Cannot read property 'top' of undefined

### ISSUE THREAD

**Issue by caneroj1** [fundon/atom-minimap#195]
Not a lot of help here with steps to reproduce: I literally opened Atom and received this error.

**Atom Version**: 0.166.0
**System**: Mac OS X 10.10.1
**Thrown From**: [minimap](https://github.com/fundon/atom-minimap) package, v3.3.4

### Stack Trace

Uncaught TypeError: Cannot read property 'top' of undefined

```
At /Users/joecanero/.atom/packages/minimap/lib/minimap-view.coffee:353

TypeError: Cannot read property 'top' of undefined
  at MinimapView.module.exports.MinimapView.updateScrollY (/Users/joecanero/.atom/packages/minimap/lib/minimap-view.coffee:353:64)
  at MinimapView.updateScrollY (/Users/joecanero/.atom/packages/minimap/lib/minimap-view.coffee:1:1)
  at MinimapView.module.exports.MinimapView.updateScroll (/Users/joecanero/.atom/packages/minimap/lib/minimap-view.coffee:368:6)
  at MinimapView.updateScroll (/Users/joecanero/.atom/packages/minimap/lib/minimap-view.coffee:1:1)
  at /Users/joecanero/.atom/packages/minimap/lib/minimap-view.coffee:268:8

```

### Commands

```
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store"
    ],
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v0.21.0
linter, v0.7.3
linter-rubocop, v0.2.1
minimap, v3.3.4

# Dev
No dev packages
```

/cc @atom/core

**Comment by caneroj1** [comment]
So as I continue to use Atom, I keep getting the error. It's happening every time I open a new file.

**Comment by abe33** [comment]
You should really update minimap to the latest version, actually the last version is 3.5.0 and you are using 3.3.4. A lot of things have changed in Atom and previous versions are likely to break at some point.

**Comment by caneroj1** [comment]
Yikes. I updated it and I haven't received any issues. Thanks! I'm going to close this.
