### ISSUE TITLE
Mini Map moves after update

### ISSUE THREAD

**Issue by covard** [fundon/atom-minimap#196]
I have MiniMap on the left side of my editor. Every time it updates it moves to the right. I have to close and open Atom to get it to move back to the left.

**Comment by abe33** [comment]
Thanks for the report, I'll take a look at that, probably an issue with the flex order.

**Comment by covard** [comment]
Great thanks.

**Comment by abe33** [comment]
I believe this issue was fixed with v4. I'll close it for now. I'll reopen if needed.
