### ISSUE TITLE
Uncaught TypeError: Cannot read property 'tokens' of undefined

### ISSUE THREAD

**Issue by dstroot** [fundon/atom-minimap#198]
[Enter steps to reproduce below:]

1. just clicked and tried to drag on minimap as is possible with ST

**Atom Version**: 0.166.0
**System**: Mac OS X 10.10.1
**Thrown From**: [minimap](https://github.com/fundon/atom-minimap) package, v3.5.2

### Stack Trace

Uncaught TypeError: Cannot read property 'tokens' of undefined

```
At /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/display-buffer.js:958

TypeError: Cannot read property 'tokens' of undefined
  at DisplayBuffer.module.exports.DisplayBuffer.screenPositionForPixelPosition (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/display-buffer.js:958:50)
  at MinimapView.module.exports.MinimapView.onMouseDown (/Users/Dan/Dropbox/Mackup/.atom/packages/minimap/lib/minimap-view.coffee:500:38)
  at space-pen-div.<anonymous> (/Users/Dan/Dropbox/Mackup/.atom/packages/minimap/lib/minimap-view.coffee:1:1)

```

### Commands

```
     -0:00.0 open-recent:open-recent-path-2 (ul.list-inline.tab-bar.inset-panel)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store",
      "._*"
    ],
    "followSymlinks": true,
    "disabledPackages": [
      "sublime-tabs",
      "highlight-line",
      "language-objective-c",
      "language-perl",
      "language-php",
      "language-mustache",
      "language-java"
    ],
    "themes": [
      "atom-dark-ui",
      "monokai"
    ],
    "projectHome": "/Users/Dan/Code",
    "destroyEmptyPanes": false
  }
}
```

### Installed Packages

```coffee
# User
atom-color-highlight, v3.0.2
color-picker, v1.2.6
docblockr, v0.5.8
editorconfig, v0.2.3
file-icons, v1.4.4
language-jade, v0.3.0
linter, v0.9.1
linter-csslint, v0.0.11
linter-jscs, v1.4.9
linter-jshint, v0.1.0
linter-less, v0.3.1
linter-tidy, v0.0.1
local-history, v2.0.0
minimap, v3.5.2
monokai, v0.9.0
open-recent, v2.0.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by abe33** [comment]
Thanks for the report, I'll fix that asap.

**Comment by abe33** [comment]
Hmm, I can't reproduce it, does it occurs repeatedly? 

I also see that the last command comes from the open-recent package, is there a recent update of this package? Does this error occurs when opening a project the classical way?

**Comment by sdouche** [comment]
Same error here. Just clicked on the minimap
Atom Version: 0.165.0
System: Ubuntu 14.10
Thrown From: minimap package, v3.5.3

Stack Trace
```
TypeError: Cannot read property 'tokens' of undefined
  at DisplayBuffer.module.exports.DisplayBuffer.screenPositionForPixelPosition (/opt/atom/resources/app/src/display-buffer.js:940:50)
  at MinimapView.module.exports.MinimapView.onMouseDown (/home/sdouche/.atom/packages/minimap/lib/minimap-view.coffee:500:38)
  at space-pen-div.<anonymous> (/home/sdouche/.atom/packages/minimap/lib/minimap-view.coffee:1:1)
```

**Comment by muchweb** [comment]
Same error here. Happened when I have split the view and then destroyed the split.

**Comment by dstroot** [comment]
Occurs pretty regularly - I opened a folder without using the 'open-recent' package and same thing but it took me a few attempts with different files to get it to happen.  Interestingly my package.json seems to work best.

**Comment by abe33** [comment]
The new click handler now use the same implementation as with v4 preview, meaning that it doesn't rely on `screenPositionForPixelPosition` to compute the row at position. I hope it'll fix the issue, if not I'll reopen this ticket.
