### ISSUE TITLE
Travis build should fail when tests don't execute

### ISSUE THREAD

**Issue by DinisCruz** [fundon/atom-minimap#214]
I was looking at your travis integration and noticed that this one https://travis-ci.org/fundon/atom-minimap/builds/46258692 showed as a successful build, but it is showing as pass

![image](https://cloud.githubusercontent.com/assets/656739/5691300/a61a77f0-98b7-11e4-9751-eb03d339a630.png)
....
![image](https://cloud.githubusercontent.com/assets/656739/5691306/d7355f1c-98b7-11e4-88f8-a7acf3c7acad.png)

Here is a previous build which passed and tests executed ok

![image](https://cloud.githubusercontent.com/assets/656739/5691302/c07c811a-98b7-11e4-9b7f-7c731a114d4c.png)

**Comment by abe33** [comment]
This is not that tests doesn't execute, it's that some delayed code still gets executed after the test execution. The tests ran, the results were collected, but some code still gets executed beyond that, leading to the errors we see here.
React related errors for instance (`Invariant Violation`) can't comes from the Minimap as it doesn't use react, the `TextEditor` do.

**Comment by abe33** [comment]
These issues are no longer present in the latest build.

**Comment by DinisCruz** [comment]
great, thanks for the update.

Looks good
