### ISSUE TITLE
minimap does not get mouse up event if right clicked while left mouse button is down.

### ISSUE THREAD

**Issue by despairblue** [fundon/atom-minimap#227]
```javascript
TypeError: Cannot read property 'getHeight' of null
  at Minimap.module.exports.Minimap.getVisibleHeight (/home/despairblue/.atom/packages/minimap/lib/minimap.coffee:86:25)
  at atom-text-editor-minimap.MinimapElement.drag (/home/despairblue/.atom/packages/minimap/lib/minimap-element.coffee:382:27)
  at HTMLBodyElement.<anonymous> (/home/despairblue/.atom/packages/minimap/lib/minimap-element.coffee:367:32)

```

## Repro Steps

1. left click'n hold on the minimap
2. right click (works probably only with a normal pc mouse, not with magic trackpads/mice)

**Expected:** minimap should stop following the mouse cursor
**Actual:** minimap keeps following the mouse cursor, changing the buffer, pane, application does not matter, closing the buffer leads to the above error repeatedly

## Command History

```
     -2:08.4 pane:before-item-destroyed (atom-pane.pane.active)
     -2:08.4 pane-container:active-pane-item-changed (atom-pane-container.panes)
     -2:08.3 editor:detached (atom-text-editor.editor)
     -2:08.3 editor:will-be-removed (atom-text-editor.editor)
     -2:08.3 editor:detached (atom-text-editor.editor)
     -2:08.3 editor:will-be-removed (atom-text-editor.editor)
     -2:08.3 pane:item-removed (atom-pane.pane.active)
     -1:48.7 window:toggle-dev-tools (a.btn.btn-error)
     -0:02.5 command-palette:toggle (atom-pane.pane.active)
     -0:00.0 core:confirm (atom-text-editor.editor.mini)
     -0:00.0 bug-report:open (atom-pane.pane.active)
```

## Versions

* **Atom:**       0.174.0
* **Atom-Shell:** 0.20.5
* **OS:**         linux 3.14.26-1-lts
* **Misc**
    * apm  0.120.0
    * npm  1.4.4
    * node 0.10.35
    * python 3.4.2
    * git 2.2.2

---

<small>This report was created in and posted from the Atom editor using the package `bug-report` v0.5.3.</small>

**Comment by abe33** [comment]
Thanks for the report, I think I know what the fix is, I'll push a patch tomorrow.

**Comment by abe33** [comment]
Can you tell me if the problem is still present with the latest versions (4.0.2 or 4.1.0)?

**Comment by despairblue** [comment]
fixed :clap:
