### ISSUE TITLE
ThemeManager.onDidReloadAll is deprecated.

### ISSUE THREAD

**Issue by jerone** [fundon/atom-minimap#228]
According Atom Deprecation Cop:

> ThemeManager.onDidReloadAll is deprecated.
> Use `::onDidChangeActiveThemes` instead.
> ```
> ThemeManager.onDidReloadAll (c:\Users\xxx\AppData\Local\atom\app-0.174.0\resources\app\src\theme-manager.js:81:12)
> MinimapView.initialize (c:\Users\xxx\.atom\packages\minimap\lib\minimap-view.coffee:135:35)
> ```

**Atom**: 0.174.0
**Atom Deprecation Cop**: 0.32.0

**Comment by abe33** [comment]
Thanks for the report, I'll fix that soon.

**Comment by abe33** [comment]
I forgot to close this issue, but it fixed in one of the 3.5.x release.
