### ISSUE TITLE
minimap height doesn't track the height of the editor

### ISSUE THREAD

**Issue by mark-hahn** [fundon/atom-minimap#229]
When I insert a "panel" below the editor the editor properly adjusts its height to accommodate the new sibling `div`.  However, the minimap stays at the old height of the editor.  So it doesn't line up properly with the editor.

![kblkjbhkjb kjb](https://cloud.githubusercontent.com/assets/811455/5813034/2d810338-a02b-11e4-9604-dddaf590ddfb.gif)

---

I tried this fix in my local copy of atom-minimap and it worked fine.  The edit is just to add the last two lines.

    updateMinimapSize: =>
      return unless @indicator?

      {width, height} = @getMinimapClientRect()
      editorViewRect = @getEditorViewClientRect()
      miniScrollViewRect = @renderView.getClientRect()

      evw = editorViewRect.width
      evh = editorViewRect.height

      @css height: evh, bottom: height - evh    # new line
      height = evh                              # new line

I tried to do a PR, but for some reason I can't get my fork of atom-minimap to run properly.  This is true even when I remove my changes.  Let me know if you want me to work more on the PR.

**Comment by fundon** [comment]
Welcome a PR.
I added the changes for testing, it's working for me when open a panel, but it was failure.

**Comment by mark-hahn** [comment]
I'll try to get my fork to work and give you a PR.

**Comment by mark-hahn** [comment]
I'm having trouble getting a clean fork of minimap to run.  I must be doing somethings stupid.

- I forked the latest master branch of this repo to mark-hahn/atom-minimap.  
- I deleted the published package at `~/.atom/packages/atom-minimap`.
- I cloned my fork into that location
- I went to the new folder and did `apm install`

I reloaded atom and toggled minimap.  It appeared empty.  There is nothing in `minimap-canvas`.

Can you think of what I might be doing wrong?

**Comment by fundon** [comment]
Go to the `~/.atom/packages/atom-minimap` then `npm install -d`, add `-d` flag that debug mode will be enabled.

**Comment by fundon** [comment]
@mark-hahn See https://atom.io/docs/latest/debugging

```
git clone youfored@atom-minimap
cd atom-minimp
apm link
```

**Comment by abe33** [comment]
@mark-hahn Were you using v3 or v4 when you encountered the resize issue?

**Comment by mark-hahn** [comment]
The problem was that an `apm link` was needed to create the `minimap` folder from `atom-minimap`.  This is the first time I've ever had to use `apm link`.  I store all packages in `~/.atom/packages`.  I'll work on my PR now.

BTW, I find that having a different name on the repo and the package a real PITA.  This problem I just had is a good example.  I keep going to the wrong folder and I constantly type the wrong version into command lines.  Sorry for the rant.

**Comment by mark-hahn** [comment]
> Were you using v3 or v4 when you encountered the resize issue?

V3 -- I haven't tried V4 yet.

**Comment by fundon** [comment]
Do you mean `minimap` and `atom-minimap`?
The `apm` will read `package.json`, so it is no problem. :)

**Comment by mark-hahn** [comment]
> The apm will read package.json, so it is no problem. :)

The only problem it causes is user confusion, as I said before.  To me it
is a violation of an accepted standard for package naming.  I know of no
other package that does this.

I'm not saying this is a big problem that needs fixing.  I'm just
complaining about the trouble it has caused me.

**Comment by fundon** [comment]
The `atom-minimap` just a repo-name.
Maybe named  `minimap` is better, like you said.
The `package.json` defined the metadata of package.
The `name` of `package.json` is real package name.

I think maybe we can change repo-name to `minimap` in v4 #217.
We will consider that. 
Thanks for your suggestion.

**Comment by mark-hahn** [comment]
Thank you for listening.

**Comment by mark-hahn** [comment]
When I add my patch the minimap won't toggle off.  I've traced the problem but I don't understand it and I don't understand how my CSS changes could cause it.

I put a break on `MinimapView.prototype.destroy`.  When toggling off minimap that method is called three or four times and on the last call it works and the minimap disappears.  But then when I let the code continue the minimap appears again.

The reason it appears again is because `Pane.prototype.observeActiveItem` is being called which is calling `MinimapView.prototype.onActiveItemChanged`.

Any idea what is going on?

@abe33, should I switch to working on V4 and just ignore V3?  Is V3 going away?  This overlap problem has been there a while and it wouldn't hurt to be there a while longer.

**Comment by mark-hahn** [comment]
> I added the changes for testing, it's working for me when open a panel, but it was failure when closing.

I see that problem also but it has nothing to do with my patch.  There is a conflict between minimap and some other package.  I disabled all other packages (thank you `package-cop`) and the problem went away.  I will isolate what package is conflicting when I get the time.

I will submit the PR soon.

**Comment by abe33** [comment]
I've merged the PR, I'll try releasing a new version in the evening (Greenwich timezone). 

@mark-hahn It'll be great if you could try the v4 preview, I believe most issues regarding sizing have been fixed using the same DOM polling trick that TextEditorElement is using. And I need feedback on this version before rolling it as the default.

**Comment by mark-hahn** [comment]
V4 had the same problem as V3 and this patch fixed both.

Note that minimap is not detecting the change on its own.  I have t call `updateMinimapView` before and  after I change the DOM by appending my DIV.

**Comment by abe33** [comment]
Using v4 needs a restart to be effective (the package exports is patched during the activation when v4 is enabled).
And v4 doesn't use `MinimapView` at all, but `MinimapElement`. The latter use `display: flex` (which prevent this problem) with DOM polling to catch size changes (which prevent canvas stretch/squeeze issues).

**Comment by mark-hahn** [comment]
I was wrong.  V4 doesn't have the problem, with or without the patch.
Should I make the patch conditional on V3?

**Comment by mark-hahn** [comment]
FYI: In V4 I was happy to see that I don't have to call `updateMinimapView` from my package when I change the editor size.  Your flexbox is working well.  Running `updateMinimapView` and my new minimap patch don't seem to do any harm in V4.  So I don't have to check the version of minimap, right?

**Comment by mark-hahn** [comment]
> using the same DOM polling trick that TextEditorElement is using.

Just curious.  Is this a tricky trick or does it just read the size every N ms?

**Comment by abe33** [comment]
Just a read in a setItnterval callback. 

For reference, the `TextEditorComponent::pollDOM` method: 
https://github.com/atom/atom/blob/master/src/text-editor-component.coffee#L809 

And the `MinimapElement::pollDOM` method: 
https://github.com/fundon/atom-minimap/blob/master/lib/minimap-element.coffee#L301

**Comment by mark-hahn** [comment]
It would be nice if there was service to register an element and get a
callback when the size changes.  Then there would only be one overhead
routine.

**Comment by abe33** [comment]
Sure, or the w3c and ecma could do their work properly and fix that shit in the specs (with element queries and parent selectors) :).
