### ISSUE TITLE
Cannot Disable or unistall Minimap

### ISSUE THREAD

**Issue by djds4rce** [fundon/atom-minimap#237]
Uninstalling minimap breaks the folder search functionality in atom. https://github.com/atom/atom/issues/5214
![atom bug](https://cloud.githubusercontent.com/assets/350933/5870458/a3714d26-a2f3-11e4-9596-710d7c88e0f5.PNG)

**Comment by abe33** [comment]
I'll need more details than just a screenshot of an empty pane...
What was the version of minimap you had installed, what version of atom are you running, etc.

**Comment by djds4rce** [comment]
Atom Version 0.175.0 and Minimap 0.2.0. Its not empty pane, you can see that in the summary it shows that 11010 results found but doesnt display it.

**Comment by abe33** [comment]
Minimap 0.2.0? :scream: 
Are you serious? 
Current version is 3.5.6 and 4.0.0 is in the pipe. You really should update minimap, the Atom API has changed so much till that time that it's obvious it's gonna break somewhere (hence the updates...).

**Comment by djds4rce** [comment]
I am really sorry It was a wrong copy pasta. The version is actually 3.5.6.

**Comment by abe33** [comment]
Ok, can you try with the `v4 preview` setting enabled (needs a restart)?

**Comment by djds4rce** [comment]
Enabled V4 but issue still present after a restart.

**Comment by abe33** [comment]
I can't reproduce it (see below for animated gifs, warning, they're quite heavy)

Disabling the package: 
![screen 1](http://i.imgur.com/Kck490S.gif)

Uninstalling the package: 
![screen 2](http://i.imgur.com/ntr7aii.gif)

And I won't see what in the minimap could affect the project search, my guess is that it has nothing to do with the minimap, but maybe another package or something else (custom styles, init, etc.).

**Comment by djds4rce** [comment]
You can Check this issue where there is one more person reproducing it. https://github.com/atom/atom/issues/5214.

**Comment by zephraph** [comment]
Okay, this doesn't reflect my experience at all. I had this issue last night (see the original [issue](https://github.com/atom/atom/issues/5214)) and my search didn't work _while minimap was installed_. Removing minimap actually fixed my problem. The issue is, it isn't consistent. Everything works fine on my work computer though. Both have the latest version of atom (0.175 as of this posting) and minimap (3.5.6).

**Comment by abe33** [comment]
@zephraph So there must be something beside minimap. Maybe you have an old version of the `minimap-find-and-replace` plugin installed because there's just no code in the whole minimap source that works with `find-and-replace`. If it works on one computer and not the other it's likely that the configuration is different, maybe one has an obsolete version of a plugin while the other is up to date.

**Comment by zephraph** [comment]
Maybe. 

I freshly installed Atom last night on my home pc (where the issue occurred). I only had three packages enabled and I disabled those one by one. Minimap was last and after that was disabled my search results began populating. I reinstalled one of the other packages and installed several new packages and it still worked. Adding minimap back again caused it to break. 

With that being said I have had atom installed on that computer before. There is a possibility that there were fragments from the last install that broke things. I'll clean everything out tonight and reinstall to see if I can reproduce the issue.

**Comment by abe33** [comment]
And there's no error in the console?

**Comment by zephraph** [comment]
I stand corrected. It just started happening on my work PC as well. 

![search](https://cloud.githubusercontent.com/assets/3087225/5876598/09e655bc-a2de-11e4-8ce6-b3b800d03f16.PNG)

After disabling minimap and reloading the window:

![search2](https://cloud.githubusercontent.com/assets/3087225/5876677/b5a445e4-a2de-11e4-8acb-b3618dbac56d.PNG)

**Comment by zephraph** [comment]
I've tested this and double tested. Removing all packages except minimap leaves me with the issue. Disabling minimap fixes the issue. Re-enabling minimap brings the issue back.

**Comment by abe33** [comment]
Hmm, what are the versions of `highlight-selected` and `minimap-highlight-selected`? 
Now that I think about it I fixed something regarding mini editors in `minimap-highlight-selected` (see https://github.com/abe33/minimap-highlight-selected/commit/3d78a2f89d57ef29557b44bcc1608243a5133270).

**Comment by zephraph** [comment]
It's the latest on both; 0.7.0 and 3.1.0 respectively. I've got them both uninstalled right now, with only minimap installed. I've been reloading the window in between tests, but I've also completely restarted Atom with the same net result: Having minimap enabled prevents me from using file search. 

Strangely, I swear this was working yesterday. Maybe I'm going crazy, heh.

**Comment by grizzilus** [comment]
I don't think this is directly related to the minimap package. If I use a fresh installation of Atom 0.175 (linux) and _only_ install the `merge-conflicts` package I get the same result. In the original issue on the atom/atom repo someone mentioned the `command-logger` package had a similar effect. So it is most likely a common component of the current API used by all of these packages that is causing this. I think the original issue on the atom/atom repo should be reopened and this should be closed.

**Comment by zephraph** [comment]
I agree, this issue should be closed.
