### ISSUE TITLE
Structured text loses format

### ISSUE THREAD

**Issue by rsalmei** [fundon/atom-minimap#242]
It seems to not be using a fixed size font.

**Comment by rsalmei** [comment]
In text like this, sublime minimap shows the second column perfectly aligned (worth mention that it is using tabs):
napsao-qa-nix-croupier-place-1.qa.vmcommerce.intra				place-br-qa-1
napsao-qa-nix-croupier-place-2.qa.vmcommerce.intra				place-br-qa-2
napsao-qa-nix-croupier-workflow-1.qa.vmcommerce.intra			workflow-br-qa-1
napsao-qa-nix-croupier-workflow-2.qa.vmcommerce.intra			workflow-br-qa-2
napsao-qa-nix-croupier-search-1.qa.vmcommerce.intra				search-br-qa-1
napsao-qa-nix-croupier-search-2.qa.vmcommerce.intra				search-br-qa-2
napsao-qa-nix-croupier-dealer-1.qa.vmcommerce.intra				dealer-br-qa-1
napsao-qa-nix-croupier-dealer-2.qa.vmcommerce.intra				dealer-br-qa-2
napsao-qa-nix-croupier-backoffice-1.qa.vmcommerce.intra			backoffice-br-qa-1
napsao-qa-nix-croupier-backoffice-2.qa.vmcommerce.intra			backoffice-br-qa-2
napsao-nix-qa-oms-services1.qa.vmcommerce.intra					services-qa-1
napsao-nix-qa-oms-services2.qa.vmcommerce.intra					services-qa-2

**Comment by abe33** [comment]
It doesn't use a font, it renders chars as rectangles on a canvas. 
Also, pasting a bunch of text doesn't help understand your issue, a screenshot would have been better.

**Comment by rsalmei** [comment]
Sorry about that, forgot it would lose formatting.
And I have already sorted it out! It was the setting Tab Length, which has a default value of 2. Setting it to 4 fixed the problem.
But it is great to know chars are rectangles on a canvas, thanks. Please close this issue.
