### ISSUE TITLE
Text granularity

### ISSUE THREAD

**Issue by rsalmei** [fundon/atom-minimap#243]
Comparing with sublime, which shows a perfect representation of the graphic spaces between letters, here the lines become full blocks of pixels.
Maybe it is not hidpi enabled yet, but it appears to render fonts with pixelsize 2 or even 3.
Tried disabling hardware acceleration, no effect.
Using a macbook retina.

**Comment by abe33** [comment]
We're using a canvas and drawing blocks for chars where sublime uses the GPU to rescale a bitmap, the same results can't be achieved we the current possibilities offered by web technologies.

You can always plays with the minimap settings if you find the default render too large, my own setup use 1px char width, 1px char height and 1px of interline.

**Comment by rsalmei** [comment]
I understand...
Thank you!
