### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by jcdevil** [fundon/atom-minimap#246]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (/Applications/Atom.app/Contents/Resources/app/src/atom.js:53:11)
Minimap.activate (/Users/jcdevil/.atom/packages/minimap/lib/minimap.coffee:95:9)
```

**Comment by abe33** [comment]
You should update the minimap package to v4, this was fixed recently.
