### ISSUE TITLE
Unable to install minimap package on Windows 8.1 with Atom v.0.176

### ISSUE THREAD

**Issue by joshku** [fundon/atom-minimap#247]
Hi, I tried to do a package install with Atom and I am unable to install minimap. Not sure what is going on but there is the error message that I got. I just did a fresh install of Atom to my Windows 8.1 laptop.

npm ERR! Failed to clone git+https://github.com/Benvie/harmony-collections.git#e81b4b808359e2def9eeeabfdee69c2989e1fe96 from https://github.com/Benvie/harmony-collections.git Cloning into 'C:\Users\Josh\AppData\Local\Temp\npm-1952-09bd2c23\git-cache-d860487d2c7d\e81b4b808359e2def9eeeabfdee69c2989e1fe96'...
npm ERR! Failed to clone git+https://github.com/Benvie/harmony-collections.git#e81b4b808359e2def9eeeabfdee69c2989e1fe96 from https://github.com/Benvie/harmony-collections.git fatal: '/cygdrive/c/Users/Josh/.atom/.node-gyp/.atom/.apm/_git-remotes/https-github-com-Benvie-harmony-collections-git-df214100/c:\Users\Josh.atom.node-gyp.atom.apm_git-remotes\https-github-com-Benvie-harmony-collections-git-df214100' does not appear to be a git repository
npm ERR! Failed to clone git+https://github.com/Benvie/harmony-collections.git#e81b4b808359e2def9eeeabfdee69c2989e1fe96 from https://github.com/Benvie/harmony-collections.git fatal: Could not read from remote repository.
npm ERR! Failed to clone git+https://github.com/Benvie/harmony-collections.git#e81b4b808359e2def9eeeabfdee69c2989e1fe96 from https://github.com/Benvie/harmony-collections.git
npm ERR! Failed to clone git+https://github.com/Benvie/harmony-collections.git#e81b4b808359e2def9eeeabfdee69c2989e1fe96 from https://github.com/Benvie/harmony-collections.git Please make sure you have the correct access rights
npm ERR! Failed to clone git+https://github.com/Benvie/harmony-collections.git#e81b4b808359e2def9eeeabfdee69c2989e1fe96 from https://github.com/Benvie/harmony-collections.git and the repository exists.
npm ERR! Failed to clone git+https://github.com/Benvie/harmony-collections.git#e81b4b808359e2def9eeeabfdee69c2989e1fe96 from https://github.com/Benvie/harmony-collections.git
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "c:\Users\Josh\AppData\Local\atom\app-0.176.0\resources\app\apm\bin\\node.exe" "c:\Users\Josh\AppData\Local\atom\app-0.176.0\resources\app\apm\node_modules\npm\bin\npm-cli.js" "--globalconfig" "c:\Users\Josh\AppData\Local\atom\app-0.176.0\resources\app\apm\.apmrc" "--userconfig" "c:\Users\Josh\.atom\.apmrc" "install" "C:\Users\Josh\AppData\Local\Temp\d-11513-9844-uadpna\package.tgz" "--target=0.20.0" "--arch=ia32" "--msvs_version=2013"
npm ERR! node v0.10.35
npm ERR! npm v2.3.0
npm ERR! code 128

npm ERR! Command failed: Cloning into 'C:\Users\Josh\AppData\Local\Temp\npm-1952-09bd2c23\git-cache-d860487d2c7d\e81b4b808359e2def9eeeabfdee69c2989e1fe96'...
npm ERR! fatal: '/cygdrive/c/Users/Josh/.atom/.node-gyp/.atom/.apm/_git-remotes/https-github-com-Benvie-harmony-collections-git-df214100/c:\Users\Josh.atom.node-gyp.atom.apm_git-remotes\https-github-com-Benvie-harmony-collections-git-df214100' does not appear to be a git repository
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR! http://github.com/npm/npm/issues

**Comment by fundon** [comment]
Thanks for your report.

@abe33 Should we update the dependencies?

```
$ atom-minimap npm list                                                                      
minimap@4.0.2 /Users/fundon/dev/fundon/atom-minimap
├─┬ atom-space-pen-views@0.21.0
│ ├── fuzzaldrin@2.1.0
│ └── space-pen@4.3.0
├── delegato@1.0.0
├── event-kit@0.7.2
├─┬ fs-plus@2.3.2
│ ├── async@0.2.10
│ ├── mkdirp@0.3.5
│ └── rimraf@2.2.8
├─┬ grim@0.12.0
│ └─┬ emissary@1.3.1
│   ├── harmony-collections@0.3.7 (git+https://github.com/Benvie/harmony-collections.git#e81b4b808359e2def9eeeabfdee69c2989e1fe96)
│   └─┬ property-accessors@1.1.0
│     └── harmony-collections@0.3.7 (git+https://github.com/Benvie/harmony-collections.git#e81b4b808359e2def9eeeabfdee69c2989e1fe96)
├── mixto@1.0.0
├── semver@2.3.2
├── temp@0.5.0
├─┬ theorist@1.0.2
│ ├─┬ emissary@1.3.1
│ │ └── harmony-collections@0.3.7 (git+https://github.com/Benvie/harmony-collections.git#e81b4b808359e2def9eeeabfdee69c2989e1fe96)
│ └─┬ property-accessors@1.1.0
│   └── harmony-collections@0.3.7 (git+https://github.com/Benvie/harmony-collections.git#e81b4b808359e2def9eeeabfdee69c2989e1fe96)
└─┬ underscore-plus@1.6.1
  └── underscore@1.6.0
```

**Comment by fundon** [comment]
Same issue atom/atom/issues/5285

**Comment by abe33** [comment]
@fundon Yep, I think we no longer need `property-accessors` and `grim` and I think even `theorist` could be removed. I'll have to try that after work.

**Comment by fundon** [comment]
@abe33 By the way, the Atom already switched to io.js?

**Comment by abe33** [comment]
Starting from 0.177 yes, and Chrome 40 as well (see https://twitter.com/atomeditor/status/562681016239017984).

**Comment by fundon** [comment]
https://github.com/atom/emissary/pull/10

I thought it was fixed in https://github.com/atom/emissary.
