### ISSUE TITLE
Minimap does not refresh when switching syntax theme

### ISSUE THREAD

**Issue by KeitIG** [fundon/atom-minimap#250]
Hi, 

all is in title :) (here switching from Atom Dark to Monokai)

![capture du 2015-02-04 14 11 09](https://cloud.githubusercontent.com/assets/1311607/6040936/cb716fee-ac77-11e4-9b9f-ae56cfbb694a.png)

**Comment by abe33** [comment]
Thanks for the report, not sure why and when it was broken but I'll make sure to make it work again.
