### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by zefredz** [fundon/atom-minimap#253]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (/usr/share/atom/resources/app/src/atom.js:54:11)
Minimap.activate (/home/fminne/.atom/packages/minimap/lib/minimap.coffee:98:11)
```

**Comment by abe33** [comment]
Please update to the latest version (4.x), we're no longer using workspaceView since at least 2 minor versions.

**Comment by zefredz** [comment]
OK, thank you. Atom seems to have updated the package but, somehow, the issue was still reported after the update. It works fine today.

Sorry to have bothered you with a false issue.

**Comment by abe33** [comment]
No problem :)
