### ISSUE TITLE
Toggle doesn't work properly

### ISSUE THREAD

**Issue by SalGnt** [fundon/atom-minimap#255]
When the Minimap is active the Toggle command doesn't hide it.
I'm using Atom Version `0.177.0`.

**Comment by abe33** [comment]
Thanks for the report, I can confirm it. I'll try fixing that soon.

**Comment by fundon** [comment]
@abe33 I fixed it. Please review.

**Comment by SalGnt** [comment]
It works fine now, thank you!

**Comment by fundon** [comment]
Fixed in https://github.com/fundon/atom-minimap/commit/6e5a18e7f825acf746d1564ffa9ceee0a9e95a6c

**Comment by fundon** [comment]
@SalGnt Released in v4.1.1.

**Comment by SalGnt** [comment]
@fundon Got it, thanks!
