### ISSUE TITLE
Stopped working in 0.177.0

### ISSUE THREAD

**Issue by thislooksfun** [fundon/atom-minimap#256]
After updating to Atom 0.177.0 and Minimap 4.1.0, the minimap stopped working.
Settings:
![screen shot 2015-02-05 at 7 32 27 pm](https://cloud.githubusercontent.com/assets/5367333/6072978/cfa5769a-ad6d-11e4-9e49-a7326c2f23db.png)
Screenshot:
![screen shot 2015-02-05 at 7 32 39 pm](https://cloud.githubusercontent.com/assets/5367333/6072980/cfb2028e-ad6d-11e4-9490-83707da16800.png)
It's probably something I have done, but I see no reason why it wouldn't be working.

**Comment by fundon** [comment]
It's working on my machine.

**Comment by abe33** [comment]
FWIW have you tried disabling the hardware acceleration?

**Comment by thislooksfun** [comment]
I tried both disabling all other (community) plugins, and disabled hardware acceleration, and it still doesn't work. Any other ideas? I love this plugin...

**Comment by fundon** [comment]
@thislooksfun Thanks reporting.

Maybe it's same as #255.

You can try this branch #258

**Comment by fundon** [comment]
@thislooksfun Update to the latest version(v4.1.2).

**Comment by thislooksfun** [comment]
Nope. Still doesn't work. I'm going to try re-installing it.

**Comment by fundon** [comment]
Good catch!  Thanks @thislooksfun

**Comment by thislooksfun** [comment]
No problem! Just a fair amount of trial and error. Not like I had anything better to do. \:P

**Comment by fundon** [comment]
I'm trying to fix that.

**Comment by fundon** [comment]
@thislooksfun Can you try this branch? https://github.com/fundon/atom-minimap/tree/fix/soft_wrap_at_preferred_line_length

**Comment by fundon** [comment]
Fixed in v4.1.3.

**Comment by fundon** [comment]
If it's still same issue, re-open it.

**Comment by thislooksfun** [comment]
It appears to be working now. However, I have also found that having the line length that high is a bad idea on it's own. Scrolling gets _really_ slow. Thanks for fixing it though! Keep up the great work!

**Comment by abe33** [comment]
I should have seen it coming. We'll need to make sure the minimap canvas width never get this wide so that we avoid memory or performance hog.

@fundon If you have some time to write the tests corresponding to the fix so that we don't miss it the next time we touch the codebase.

**Comment by fundon** [comment]
@abe33 You are right, sorry. I will. :)
