### ISSUE TITLE
display nothing when split-down and height of editor equals height of content

### ISSUE THREAD

**Issue by fundon** [fundon/atom-minimap#260]
![panes](https://cloud.githubusercontent.com/assets/27926/6102470/e59b4766-b071-11e4-988e-ec62bb4c30aa.gif)

/cc @abe33

**Comment by abe33** [comment]
Hmm, that's pretty weird, what gives an inspection of the minimap in that situation? Is it the canvas drawing that fail or is a matter of layout within the minimap?

**Comment by fundon** [comment]
The canvas and the minimap-visible-area element miss the style.
 e.g. `transform: translate3d(0px, 0px, 0px) scale3d(0.5, 0.5, 1);`.

**Comment by abe33** [comment]
Ok, if you don't mind I'll take care of that issue, but it'll wait until I get back home.

**Comment by abe33** [comment]
Ok, it seems I can't reproduce that issue:

![screencast](http://i.imgur.com/E7W4llc.gif)

What is your config, maybe it happens only in a specific configuration?

**Comment by fundon** [comment]
Open a small file.

![panes2](https://cloud.githubusercontent.com/assets/27926/6125879/db6b8ed8-b155-11e4-9879-299c5e3874c9.gif)

**Comment by fundon** [comment]
@abe33 I found the point. Maybe the `seti-ui` theme brought on this issuse.

If disabled the `seti-ui`, everything is ok.

**Comment by abe33** [comment]
It could be interesting to dig this issue a bit, if themes can break the minimap we should try to find a guard against that.

Does the theme add some rules for canvas or something that pollute the minimap content?

**Comment by fundon** [comment]
Tracked css rules of the `seti-ui` theme.

```css
.tab-bar {
  height: 40px;
}
```

`40px` is a magical number.

**Comment by abe33** [comment]
Hmm, I'm not sure to understand why this value would trigger this. Now that the minimap is part of the flex layout it shouldn't be concerned by the tab-bar height.

**Comment by fundon** [comment]
I catched the code that there might be a problem.
I will make a PR. :smile:

**Comment by abe33** [comment]
BTW @fundon, I updated the Readme with a contributing section. Take a look at the format for commits, you'll be abe to use my [changelog-gen utility](https://github.com/abe33/changelog-gen) to generate the CHANGELOG content when releasing a new version ;).

**Comment by fundon** [comment]
@abe33 Thanks, OK. haha

**Comment by fundon** [comment]
Fixed in v4.1.4
