### ISSUE TITLE
Updating to “minimap@4.1.4” failed on Linux

### ISSUE THREAD

**Issue by edomato** [fundon/atom-minimap#264]
Today, when I tried to update minimap as proposed by atom it throws:
```
npm ERR! addLocal Could not install /tmp/d-115111-3677-170co37/package.tgz
npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/usr/share/atom/resources/app/apm/.apmrc" "--userconfig" "/home/edomato/.atom/.apmrc" "install" "/tmp/d-115111-3677-170co37/package.tgz" "--target=0.21.0" "--arch=x64"
npm ERR! node v0.10.35
npm ERR! npm  v2.3.0
npm ERR! path /root/.atom/.apm
npm ERR! code EACCES
npm ERR! errno 3

npm ERR! Error: EACCES, mkdir '/root/.atom/.apm'
npm ERR!  { [Error: EACCES, mkdir '/root/.atom/.apm'] errno: 3, code: 'EACCES', path: '/root/.atom/.apm' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/apm-install-dir-115111-3677-o0qln5/npm-debug.log
```
Thanks for your help.
Ernesto

**Comment by fundon** [comment]
Is there same issue, reinstall?

**Comment by abe33** [comment]
I believe this issue is not related with this package. As the error mention an access issue, it's likely that atom was install as root and you're trying to update as a simple user. You can probably `chmod` the corresponding path to force the update, but the best course would be to reinstall atom/apm so that the user can install/update packages.

**Comment by edomato** [comment]
Ok, I tried on another computer, even with a fresh install of Atom (I moved the .atom directory away) and the same problem arises.
```
npm ERR! addLocal Could not install /tmp/d-115111-2155-d8e6tw/package.tgz
npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/usr/share/atom/resources/app/apm/.apmrc" "--userconfig" "/home/edomato/.atom/.apmrc" "install" "/tmp/d-115111-2155-d8e6tw/package.tgz" "--target=0.21.0" "--arch=x64"
npm ERR! node v0.10.35
npm ERR! npm  v2.3.0
npm ERR! path /var/lib/jenkins
npm ERR! code EACCES
npm ERR! errno 3

npm ERR! Error: EACCES, mkdir '/var/lib/jenkins'
npm ERR!  { [Error: EACCES, mkdir '/var/lib/jenkins'] errno: 3, code: 'EACCES', path: '/var/lib/jenkins' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/apm-install-dir-115111-2155-fg0qrz/npm-debug.log
```

So, I guess that you could reproduce the error on a Linux box easily. Atom version is 0.178 and Linux distribution is Debian Jessie.

Thanks and let me know what can I do to help solve this problem.

**Comment by edomato** [comment]
On the other hand, what I'm seeing on the error message is that the installation of the plugin tries to create a directory called `/var/lib/jenkins` for some reason and a normal user can't do that because of the permissions restrictions.

So, maybe the problem has nothing to do with the minimap plugin but with atom itself. Do you do anything with jenkins?

Regards

**Comment by abe33** [comment]
> So, maybe the problem has nothing to do with the minimap plugin but with atom itself. Do you do anything with jenkins?

Most likely, we [do nothing jenkins-related](https://github.com/fundon/atom-minimap/search?utf8=%E2%9C%93&q=jenkins) and packages have little room to play with file permissions, and the purpose of a minimap is clearly not to do so ^^.

You'll probably have better luck posting this issue on the atom/apm repository, and think to add the `npm-debug.log` file at the same time ;).

**Comment by edomato** [comment]
Well, definitely is an atom/apm problem. What I did this time is to uninstalled the entire package and moved away the .atom directory, then I installed the atom package again and tried to install another plugin (color-picker this time) and the same error arise.

I'll post the issue in the atom/apm project instead (if it's not already reported).

Thanks for all.

**Comment by edomato** [comment]
I went to the atom repository and today there's a new version (0.179) that fixes this problem. :-)

**Comment by fundon** [comment]
Good news.
