### ISSUE TITLE
Uncaught Error: Cannot find module './minimap-quick-settings-view'

### ISSUE THREAD

**Issue by p3k** [fundon/atom-minimap#274]
[Enter steps to reproduce below:]

1. Click on the gear icon in the top right corner of the minimap

**Atom Version**: 0.179.0
**System**: linux 3.13.0-45-generic
**Thrown From**: [minimap](https://github.com/fundon/atom-minimap) package, v4.2.2

### Stack Trace

Uncaught Error: Cannot find module './minimap-quick-settings-view'

```
At module.js:353

Error: Cannot find module './minimap-quick-settings-view'
  at Module._resolveFilename (module.js:351:15)
  at Function.Module._resolveFilename (/usr/share/atom/resources/app/src/module-cache.js:383:52)
  at Function.Module._load (module.js:293:25)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at HTMLDivElement.<anonymous> (/home/tobi/.atom/packages/minimap/lib/minimap-element.coffee:171:3)

```

### Commands

```
     -2:16.6 pane:reopen-closed-item (atom-text-editor.editor)
     -1:59.6 core:save (atom-text-editor.editor)
     -1:51.9 pane:close (atom-text-editor.editor)
     -1:20.4 timecop:view (atom-workspace.workspace.scrollbars-visible-always.theme-solarized-light-syntax.theme-atom-light-ui)
     -0:53.9 application:new-file (ul.list-inline.tab-bar.inset-panel)
     -0:42.7 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-solarized-light-syntax.theme-atom-light-ui)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "solarized-light-syntax"
    ],
    "autoHideMenuBar": true
  },
  "minimap": {}
}
```

### Installed Packages

```coffee
# User
minimap, v4.2.2

# Dev
No dev packages
```

**Comment by abe33** [comment]
I think you got that issue immediately after an update? 

A restart should solve the issue. I believe Atom somehow fails to reload the new code after an update. This file was removed as part of an effort to get rid of all space-pen views and to replace them with custom elements and in that effort the file name was changed to match the Atom convention on that matter.

**Comment by p3k** [comment]
yup, sorry. after restart it works. thanks!
